# Note: Using docker-compose since it makes it much easier for us Windows users to mount volumes consistently.

version: '3'
services:
  gcc:
    image: gcc
    entrypoint: sh -c 'chmod +x /export/build.sh && /export/build.sh'
    volumes:
      - .:/export
